### ISSUE TITLE
Design Curriculum API

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/mentorHub-curriculum-api#1]
Create API to support the UI that apprentices use to manage their curriculum. 
- [ ] Create OpenApi Specification.
- [ ] Open draft PR and get reviews from UI and Data engineers.

**Comment by fazzy12** [comment]
It seems that I'm unable to assign this issue #1 to myself. I've attempted to do so, but it appears that self-assignment isn't working for me in this repository.

Could you please assign this issue to me or provide guidance on how I can do it myself?

Thank you for your assistance.
